#!/usr/bin/env bash
# Run this script ON Germany VPS (178.83.46.103) as root.
# Poland VPS cannot SSH here until /root/.ssh/id_ed25519.pub from PL is in authorized_keys.
set -euo pipefail

DOMAIN="pudge.noranx.ir"
WEBROOT="/var/www/${DOMAIN}"
CONF_PATH="/etc/nginx/sites-available/${DOMAIN}.conf"

mkdir -p "${WEBROOT}" /root/backups

if [[ ! -f "${CONF_PATH}" ]]; then
  curl -fsSL "http://82.47.63.24:8080/${DOMAIN}.conf.bootstrap" -o "${CONF_PATH}" 2>/dev/null || true
fi

if [[ ! -f "${CONF_PATH}" ]]; then
  cat > "${CONF_PATH}" <<'NGINX_EOF'
# Generated by noranx rollout — see /root/noranx_vpn_bot/infrastructure/nginx/pudge.noranx.ir.conf on PL
NGINX_EOF
  echo "ERROR: copy /root/noranx_vpn_bot/infrastructure/nginx/pudge.noranx.ir.conf from Poland VPS"
  exit 1
fi

ln -sf "${CONF_PATH}" "/etc/nginx/sites-enabled/${DOMAIN}.conf"
nginx -t
systemctl reload nginx

if [[ ! -d "/etc/letsencrypt/live/${DOMAIN}" ]]; then
  certbot certonly --webroot -w "${WEBROOT}" -d "${DOMAIN}" \
    --non-interactive --agree-tos --register-unsafely-without-email
fi

nginx -t && systemctl reload nginx

for path in /ws /trojan /vmess; do
  echo "=== ${path} ==="
  curl -si --max-time 8 -H "Host: ${DOMAIN}" \
    -H "Connection: Upgrade" -H "Upgrade: websocket" \
    -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==" \
    "http://127.0.0.1${path}" | head -2
done

echo "pudge.noranx.ir nginx deploy complete"
